# Site settings
title: Genomics Platform
theme: jekyll-theme-merlot
email:
description: DanStem & CPR: https://danstemgenomics.github.io
baseurl:
url:
twitter_username:
github_username: DanStemGenomics

# Build settings
markdown: kramdown
permalink: pretty
